/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDossiersRouteImport } from './routes/_app/dossiers'
import { Route as AppDossiersDossierIdIndexRouteImport } from './routes/_app/dossiers.$dossierId.index'
import { Route as AppDossiersDossierIdPaieRouteImport } from './routes/_app/dossiers.$dossierId.paie'
import { Route as AppDossiersDossierIdGedRouteImport } from './routes/_app/dossiers.$dossierId.ged'
import { Route as AppDossiersDossierIdFournisseursRouteImport } from './routes/_app/dossiers.$dossierId.fournisseurs'
import { Route as AppDossiersDossierIdFiscaliteRouteImport } from './routes/_app/dossiers.$dossierId.fiscalite'
import { Route as AppDossiersDossierIdFacturesRouteImport } from './routes/_app/dossiers.$dossierId.factures'
import { Route as AppDossiersDossierIdDashboardRouteImport } from './routes/_app/dossiers.$dossierId.dashboard'
import { Route as AppDossiersDossierIdComptabiliteRouteImport } from './routes/_app/dossiers.$dossierId.comptabilite'
import { Route as AppDossiersDossierIdClientsRouteImport } from './routes/_app/dossiers.$dossierId.clients'
import { Route as AppDossiersDossierIdBanqueRouteImport } from './routes/_app/dossiers.$dossierId.banque'
import { Route as AppDossiersDossierIdAuditRouteImport } from './routes/_app/dossiers.$dossierId.audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDossiersRoute = AppDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AppRoute,
} as any)
const AppDossiersDossierIdIndexRoute =
  AppDossiersDossierIdIndexRouteImport.update({
    id: '/$dossierId/',
    path: '/$dossierId/',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdPaieRoute =
  AppDossiersDossierIdPaieRouteImport.update({
    id: '/$dossierId/paie',
    path: '/$dossierId/paie',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdGedRoute = AppDossiersDossierIdGedRouteImport.update({
  id: '/$dossierId/ged',
  path: '/$dossierId/ged',
  getParentRoute: () => AppDossiersRoute,
} as any)
const AppDossiersDossierIdFournisseursRoute =
  AppDossiersDossierIdFournisseursRouteImport.update({
    id: '/$dossierId/fournisseurs',
    path: '/$dossierId/fournisseurs',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdFiscaliteRoute =
  AppDossiersDossierIdFiscaliteRouteImport.update({
    id: '/$dossierId/fiscalite',
    path: '/$dossierId/fiscalite',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdFacturesRoute =
  AppDossiersDossierIdFacturesRouteImport.update({
    id: '/$dossierId/factures',
    path: '/$dossierId/factures',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdDashboardRoute =
  AppDossiersDossierIdDashboardRouteImport.update({
    id: '/$dossierId/dashboard',
    path: '/$dossierId/dashboard',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdComptabiliteRoute =
  AppDossiersDossierIdComptabiliteRouteImport.update({
    id: '/$dossierId/comptabilite',
    path: '/$dossierId/comptabilite',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdClientsRoute =
  AppDossiersDossierIdClientsRouteImport.update({
    id: '/$dossierId/clients',
    path: '/$dossierId/clients',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdBanqueRoute =
  AppDossiersDossierIdBanqueRouteImport.update({
    id: '/$dossierId/banque',
    path: '/$dossierId/banque',
    getParentRoute: () => AppDossiersRoute,
  } as any)
const AppDossiersDossierIdAuditRoute =
  AppDossiersDossierIdAuditRouteImport.update({
    id: '/$dossierId/audit',
    path: '/$dossierId/audit',
    getParentRoute: () => AppDossiersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dossiers': typeof AppDossiersRouteWithChildren
  '/dossiers/$dossierId/audit': typeof AppDossiersDossierIdAuditRoute
  '/dossiers/$dossierId/banque': typeof AppDossiersDossierIdBanqueRoute
  '/dossiers/$dossierId/clients': typeof AppDossiersDossierIdClientsRoute
  '/dossiers/$dossierId/comptabilite': typeof AppDossiersDossierIdComptabiliteRoute
  '/dossiers/$dossierId/dashboard': typeof AppDossiersDossierIdDashboardRoute
  '/dossiers/$dossierId/factures': typeof AppDossiersDossierIdFacturesRoute
  '/dossiers/$dossierId/fiscalite': typeof AppDossiersDossierIdFiscaliteRoute
  '/dossiers/$dossierId/fournisseurs': typeof AppDossiersDossierIdFournisseursRoute
  '/dossiers/$dossierId/ged': typeof AppDossiersDossierIdGedRoute
  '/dossiers/$dossierId/paie': typeof AppDossiersDossierIdPaieRoute
  '/dossiers/$dossierId/': typeof AppDossiersDossierIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dossiers': typeof AppDossiersRouteWithChildren
  '/dossiers/$dossierId/audit': typeof AppDossiersDossierIdAuditRoute
  '/dossiers/$dossierId/banque': typeof AppDossiersDossierIdBanqueRoute
  '/dossiers/$dossierId/clients': typeof AppDossiersDossierIdClientsRoute
  '/dossiers/$dossierId/comptabilite': typeof AppDossiersDossierIdComptabiliteRoute
  '/dossiers/$dossierId/dashboard': typeof AppDossiersDossierIdDashboardRoute
  '/dossiers/$dossierId/factures': typeof AppDossiersDossierIdFacturesRoute
  '/dossiers/$dossierId/fiscalite': typeof AppDossiersDossierIdFiscaliteRoute
  '/dossiers/$dossierId/fournisseurs': typeof AppDossiersDossierIdFournisseursRoute
  '/dossiers/$dossierId/ged': typeof AppDossiersDossierIdGedRoute
  '/dossiers/$dossierId/paie': typeof AppDossiersDossierIdPaieRoute
  '/dossiers/$dossierId': typeof AppDossiersDossierIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dossiers': typeof AppDossiersRouteWithChildren
  '/_app/dossiers/$dossierId/audit': typeof AppDossiersDossierIdAuditRoute
  '/_app/dossiers/$dossierId/banque': typeof AppDossiersDossierIdBanqueRoute
  '/_app/dossiers/$dossierId/clients': typeof AppDossiersDossierIdClientsRoute
  '/_app/dossiers/$dossierId/comptabilite': typeof AppDossiersDossierIdComptabiliteRoute
  '/_app/dossiers/$dossierId/dashboard': typeof AppDossiersDossierIdDashboardRoute
  '/_app/dossiers/$dossierId/factures': typeof AppDossiersDossierIdFacturesRoute
  '/_app/dossiers/$dossierId/fiscalite': typeof AppDossiersDossierIdFiscaliteRoute
  '/_app/dossiers/$dossierId/fournisseurs': typeof AppDossiersDossierIdFournisseursRoute
  '/_app/dossiers/$dossierId/ged': typeof AppDossiersDossierIdGedRoute
  '/_app/dossiers/$dossierId/paie': typeof AppDossiersDossierIdPaieRoute
  '/_app/dossiers/$dossierId/': typeof AppDossiersDossierIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dossiers'
    | '/dossiers/$dossierId/audit'
    | '/dossiers/$dossierId/banque'
    | '/dossiers/$dossierId/clients'
    | '/dossiers/$dossierId/comptabilite'
    | '/dossiers/$dossierId/dashboard'
    | '/dossiers/$dossierId/factures'
    | '/dossiers/$dossierId/fiscalite'
    | '/dossiers/$dossierId/fournisseurs'
    | '/dossiers/$dossierId/ged'
    | '/dossiers/$dossierId/paie'
    | '/dossiers/$dossierId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dossiers'
    | '/dossiers/$dossierId/audit'
    | '/dossiers/$dossierId/banque'
    | '/dossiers/$dossierId/clients'
    | '/dossiers/$dossierId/comptabilite'
    | '/dossiers/$dossierId/dashboard'
    | '/dossiers/$dossierId/factures'
    | '/dossiers/$dossierId/fiscalite'
    | '/dossiers/$dossierId/fournisseurs'
    | '/dossiers/$dossierId/ged'
    | '/dossiers/$dossierId/paie'
    | '/dossiers/$dossierId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dossiers'
    | '/_app/dossiers/$dossierId/audit'
    | '/_app/dossiers/$dossierId/banque'
    | '/_app/dossiers/$dossierId/clients'
    | '/_app/dossiers/$dossierId/comptabilite'
    | '/_app/dossiers/$dossierId/dashboard'
    | '/_app/dossiers/$dossierId/factures'
    | '/_app/dossiers/$dossierId/fiscalite'
    | '/_app/dossiers/$dossierId/fournisseurs'
    | '/_app/dossiers/$dossierId/ged'
    | '/_app/dossiers/$dossierId/paie'
    | '/_app/dossiers/$dossierId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dossiers': {
      id: '/_app/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof AppDossiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dossiers/$dossierId/': {
      id: '/_app/dossiers/$dossierId/'
      path: '/$dossierId'
      fullPath: '/dossiers/$dossierId/'
      preLoaderRoute: typeof AppDossiersDossierIdIndexRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/paie': {
      id: '/_app/dossiers/$dossierId/paie'
      path: '/$dossierId/paie'
      fullPath: '/dossiers/$dossierId/paie'
      preLoaderRoute: typeof AppDossiersDossierIdPaieRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/ged': {
      id: '/_app/dossiers/$dossierId/ged'
      path: '/$dossierId/ged'
      fullPath: '/dossiers/$dossierId/ged'
      preLoaderRoute: typeof AppDossiersDossierIdGedRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/fournisseurs': {
      id: '/_app/dossiers/$dossierId/fournisseurs'
      path: '/$dossierId/fournisseurs'
      fullPath: '/dossiers/$dossierId/fournisseurs'
      preLoaderRoute: typeof AppDossiersDossierIdFournisseursRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/fiscalite': {
      id: '/_app/dossiers/$dossierId/fiscalite'
      path: '/$dossierId/fiscalite'
      fullPath: '/dossiers/$dossierId/fiscalite'
      preLoaderRoute: typeof AppDossiersDossierIdFiscaliteRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/factures': {
      id: '/_app/dossiers/$dossierId/factures'
      path: '/$dossierId/factures'
      fullPath: '/dossiers/$dossierId/factures'
      preLoaderRoute: typeof AppDossiersDossierIdFacturesRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/dashboard': {
      id: '/_app/dossiers/$dossierId/dashboard'
      path: '/$dossierId/dashboard'
      fullPath: '/dossiers/$dossierId/dashboard'
      preLoaderRoute: typeof AppDossiersDossierIdDashboardRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/comptabilite': {
      id: '/_app/dossiers/$dossierId/comptabilite'
      path: '/$dossierId/comptabilite'
      fullPath: '/dossiers/$dossierId/comptabilite'
      preLoaderRoute: typeof AppDossiersDossierIdComptabiliteRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/clients': {
      id: '/_app/dossiers/$dossierId/clients'
      path: '/$dossierId/clients'
      fullPath: '/dossiers/$dossierId/clients'
      preLoaderRoute: typeof AppDossiersDossierIdClientsRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/banque': {
      id: '/_app/dossiers/$dossierId/banque'
      path: '/$dossierId/banque'
      fullPath: '/dossiers/$dossierId/banque'
      preLoaderRoute: typeof AppDossiersDossierIdBanqueRouteImport
      parentRoute: typeof AppDossiersRoute
    }
    '/_app/dossiers/$dossierId/audit': {
      id: '/_app/dossiers/$dossierId/audit'
      path: '/$dossierId/audit'
      fullPath: '/dossiers/$dossierId/audit'
      preLoaderRoute: typeof AppDossiersDossierIdAuditRouteImport
      parentRoute: typeof AppDossiersRoute
    }
  }
}

interface AppDossiersRouteChildren {
  AppDossiersDossierIdAuditRoute: typeof AppDossiersDossierIdAuditRoute
  AppDossiersDossierIdBanqueRoute: typeof AppDossiersDossierIdBanqueRoute
  AppDossiersDossierIdClientsRoute: typeof AppDossiersDossierIdClientsRoute
  AppDossiersDossierIdComptabiliteRoute: typeof AppDossiersDossierIdComptabiliteRoute
  AppDossiersDossierIdDashboardRoute: typeof AppDossiersDossierIdDashboardRoute
  AppDossiersDossierIdFacturesRoute: typeof AppDossiersDossierIdFacturesRoute
  AppDossiersDossierIdFiscaliteRoute: typeof AppDossiersDossierIdFiscaliteRoute
  AppDossiersDossierIdFournisseursRoute: typeof AppDossiersDossierIdFournisseursRoute
  AppDossiersDossierIdGedRoute: typeof AppDossiersDossierIdGedRoute
  AppDossiersDossierIdPaieRoute: typeof AppDossiersDossierIdPaieRoute
  AppDossiersDossierIdIndexRoute: typeof AppDossiersDossierIdIndexRoute
}

const AppDossiersRouteChildren: AppDossiersRouteChildren = {
  AppDossiersDossierIdAuditRoute: AppDossiersDossierIdAuditRoute,
  AppDossiersDossierIdBanqueRoute: AppDossiersDossierIdBanqueRoute,
  AppDossiersDossierIdClientsRoute: AppDossiersDossierIdClientsRoute,
  AppDossiersDossierIdComptabiliteRoute: AppDossiersDossierIdComptabiliteRoute,
  AppDossiersDossierIdDashboardRoute: AppDossiersDossierIdDashboardRoute,
  AppDossiersDossierIdFacturesRoute: AppDossiersDossierIdFacturesRoute,
  AppDossiersDossierIdFiscaliteRoute: AppDossiersDossierIdFiscaliteRoute,
  AppDossiersDossierIdFournisseursRoute: AppDossiersDossierIdFournisseursRoute,
  AppDossiersDossierIdGedRoute: AppDossiersDossierIdGedRoute,
  AppDossiersDossierIdPaieRoute: AppDossiersDossierIdPaieRoute,
  AppDossiersDossierIdIndexRoute: AppDossiersDossierIdIndexRoute,
}

const AppDossiersRouteWithChildren = AppDossiersRoute._addFileChildren(
  AppDossiersRouteChildren,
)

interface AppRouteChildren {
  AppDossiersRoute: typeof AppDossiersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDossiersRoute: AppDossiersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
